import { Pickaxe, ShieldAlert } from "lucide-react"
import { useMemo, useState } from "react"
import { ScreenHeading } from "../../shell/ScreenHeading"
import { ProgressBar } from "../../components/ProgressBar"
import { useGameStore } from "../../../state/gameStore"
import type { GameState } from "../../../game/gameState"
import { getProfessionLevelProgress, professionAvailablePoints, professionPointsFromLevels, professionPointsSpent } from "../../../game/professions/professionProgression"
import { miningPerks, miningPerkById } from "../../../game/professions/mining/miningPerks"
import { getProfessionPerkPurchaseState } from "../../../game/professions/professionPerkValidation"
import { ironMasteryLevel, ironMasteryProgress, IRON_MASTERY_MILESTONES } from "../../../game/professions/mining/miningMastery"
import { getMiningStats, type MiningDerivedStats } from "../../../game/professions/mining/miningStats"
import { miningStageById } from "../../../game/professions/mining/miningData"
import { estimateMiningRates, type MiningRateEstimate } from "../../../game/professions/mining/miningRates"
import type { MiningStageDefinition } from "../../../game/professions/mining/miningTypes"

type MiningTab = "mining" | "perks" | "mastery"

export function MiningScreen() {
  const game = useGameStore((state) => state.game)
  const startMining = useGameStore((state) => state.startMining)
  const stopMining = useGameStore((state) => state.stopMining)
  const purchaseMiningPerk = useGameStore((state) => state.purchaseMiningPerk)
  const setScreen = useGameStore((state) => state.setScreen)
  const [tab, setTab] = useState<MiningTab>("mining")
  const progress = getProfessionLevelProgress(game.professions, "mining")
  const masteryProgress = ironMasteryProgress(game.professions.resourceMasteries["mastery.iron-vein"])
  const stats = getMiningStats({ ...game, stageId: game.mining.currentStageId, resourceId: game.mining.selectedResourceId })
  const rates = useMemo(() => estimateMiningRates(game), [game])
  const stage = miningStageById[game.mining.currentStageId]
  return <div className="screen mining-screen" data-debug-screen="mining" data-debug-kind="mining-screen">
    <ScreenHeading screen="mining" />
    <div className="segmented-tabs mining-tabs" role="tablist">
      <button className={"tab-button " + (tab === "mining" ? "is-active" : "")} onClick={() => setTab("mining")}>MINING</button>
      <button className={"tab-button " + (tab === "perks" ? "is-active" : "")} onClick={() => setTab("perks")}>PERK TREE</button>
      <button className={"tab-button " + (tab === "mastery" ? "is-active" : "")} onClick={() => setTab("mastery")}>MASTERY</button>
    </div>
    {tab === "mining" && <MiningOverview game={game} progress={progress} rates={rates} stats={stats} stage={stage} onStart={startMining} onStop={stopMining} onOpenHero={() => setScreen("hero")} />}
    {tab === "perks" && <MiningPerkTree game={game} onPurchase={purchaseMiningPerk} />}
    {tab === "mastery" && <MasteryPanel game={game} progress={masteryProgress} rates={rates} />}
  </div>
}

function MiningOverview({ game, progress, rates, stats, stage, onStart, onStop, onOpenHero }: { game: GameState; progress: ReturnType<typeof getProfessionLevelProgress>; rates: MiningRateEstimate; stats: MiningDerivedStats; stage: MiningStageDefinition; onStart: () => void; onStop: () => void; onOpenHero: () => void }) {
  const stageIds = ["outer-crust", "exposed-seam", "dense-vein", "rich-core", "heart-of-iron"]
  const currentIndex = stageIds.indexOf(game.mining.currentStageId)
  const canMine = Boolean(stats.toolInstanceId)
  return <><section className="mining-summary-grid">
    <div className="panel mining-profession-card"><div className="panel-header"><div className="panel-heading"><span className="panel-icon"><Pickaxe size={16} /></span><div><div className="panel-title">Mining Level {progress.level}</div><div className="panel-subtitle">{Math.floor(progress.xpIntoLevel).toLocaleString()} / {Math.floor(progress.xpRequiredForLevel).toLocaleString()} XP</div></div></div><span className="mining-points-badge">{professionAvailablePoints(game.professions, "mining")} POINTS</span></div><div className="panel-body"><ProgressBar value={progress.progressFraction * 100} variant="experience" ariaLabel="Mining experience" /><div className="mining-stat-grid"><Stat label="XP / hour" value={formatRate(rates.miningXpPerHour, 0)} /><Stat label="XP to next" value={progress.isMaxLevel ? "MAX LEVEL" : Math.ceil(progress.xpToNextLevel).toLocaleString()} /><Stat label="ETA" value={progress.isMaxLevel ? "MAX LEVEL" : formatEta(progress.xpToNextLevel, rates.miningXpPerHour)} /><Stat label="Ore / hour" value={formatRate(rates.ironOrePerHour, 0)} /></div></div></div>
    <div className="panel mining-resource-card"><div className="panel-header"><div><div className="panel-title">Iron Vein</div><div className="panel-subtitle">The only active Mining resource in V1</div></div><span className={"mining-status " + (game.mining.active ? "is-active" : "")}>{game.mining.active ? game.mining.mode === "resting" ? "EXHAUSTED" : "ACTIVE" : "READY"}</span></div><div className="panel-body"><div className="mining-stage-heading"><strong>{stage.name}</strong><span>{Math.ceil(game.mining.stageDurabilityRemaining)} / {stage.durability} durability</span></div><ProgressBar value={game.mining.stageDurabilityRemaining / stage.durability * 100} variant="health" ariaLabel="Stage durability" /><div className="mining-stage-track">{stageIds.map((id, index) => <div key={id} className={"mining-stage-node " + (index < currentIndex ? "is-complete" : index === currentIndex ? "is-current" : "")}><span>{index + 1}</span><small>{miningStageById[id].name}</small></div>)}</div></div></div>
  </section><section className="mining-main-grid">
    <div className="panel mining-loop-card"><div className="panel-header"><div><div className="panel-title">Mining Loop</div><div className="panel-subtitle">Every reward is resolved per effective-damage swing.</div></div><button className="button button-primary" disabled={!canMine && !game.mining.active} onClick={game.mining.active ? onStop : onStart}>{game.mining.active ? "STOP MINING" : canMine ? "START MINING" : "NO PICKAXE"}</button></div><div className="panel-body"><div className="mining-loop-status"><div className="mining-swing-icon"><Pickaxe size={24} /></div><div><strong>{game.mining.mode === "resting" ? "EXHAUSTED - RESTING" : game.mining.active ? "Pickaxe Swing" : "Ready"}</strong><span>{game.mining.mode === "resting" ? game.mining.restTimerRemaining.toFixed(1) + "s remaining" : game.mining.active ? Math.max(0, stats.swingInterval - game.mining.swingTimerRemaining).toFixed(1) + " / " + stats.swingInterval.toFixed(1) + " sec" : "Start mining to advance the deposit."}</span></div></div><div className="mining-stamina-row"><div><span className="tiny-label">MINING STAMINA</span><strong>{Math.ceil(game.mining.miningStamina)} / {Math.ceil(stats.maxMiningStamina)}</strong></div><ProgressBar value={game.mining.miningStamina / stats.maxMiningStamina * 100} variant="resource" ariaLabel="Mining Stamina" /></div><div className="mining-stat-grid"><Stat label="Cost / swing" value={stats.staminaCost.toFixed(1)} /><Stat label="Rest duration" value={stats.restDuration.toFixed(1) + "s"} /><Stat label="Mining Damage" value={stats.miningDamage.toFixed(1)} /><Stat label="Deposits" value={game.mining.completedDeposits.toLocaleString()} /></div></div></div>
    <div className="panel mining-tool-card"><div className="panel-header"><div><div className="panel-title">Tool</div><div className="panel-subtitle">Tools affect Mining only.</div></div></div><div className="panel-body">{stats.toolName ? <><div className="tool-heading"><Pickaxe size={22} /><div><strong>{stats.toolName}</strong><span>Pickaxe</span></div></div><div className="mining-stat-grid"><Stat label="Mining Damage" value={stats.miningDamage.toFixed(1)} /><Stat label="Required Mining" value={stats.toolName === "Iron Pickaxe" ? "10" : "1"} /></div>{game.mining.active && <small className="mining-muted">Stop Mining to change your Tool.</small>}</> : <div className="empty-state"><ShieldAlert size={22} /><strong>NO PICKAXE EQUIPPED</strong><p>Equip a Pickaxe in Hero.</p><button className="button button-secondary" onClick={onOpenHero}>OPEN HERO</button></div>}</div></div>
  </section><section className="panel mining-output-card"><div className="panel-header"><div><div className="panel-title">Per-swing Output</div><div className="panel-subtitle">Effective Damage basis; no overkill carryover.</div></div></div><div className="panel-body mining-output-grid"><Stat label="Iron Ore / swing" value={(stats.miningDamage * stage.orePerEffectiveDamage * stats.oreMultiplier).toFixed(3)} /><Stat label="Mining XP / swing" value={(stats.miningDamage * stage.skillXpPerEffectiveDamage * stats.skillXpMultiplier).toFixed(2)} /><Stat label="Mastery XP / swing" value={(stats.miningDamage * stage.masteryXpPerEffectiveDamage * stats.masteryXpMultiplier).toFixed(2)} /><Stat label="Rough Gem chance" value={(stage.roughGemChancePerReferenceDamage * 100 * stats.roughGemFindMultiplier * stats.byproductFindMultiplier).toFixed(3) + "% / 10 dmg"} /><Stat label="Black Stone chance" value={(stage.blackStoneChancePerReferenceDamage * 100 * stats.blackStoneFindMultiplier * stats.byproductFindMultiplier).toFixed(3) + "% / 10 dmg"} /><Stat label="Expected rare / hour" value={formatRate(rates.roughGemPerHour, 2) + " gem - " + formatRate(rates.blackStonePerHour, 2) + " stone"} /></div></section></>
}

function MiningPerkTree({ game, onPurchase }: { game: GameState; onPurchase: (id: string) => void }) {
  const [selected, setSelected] = useState(miningPerks[0].id)
  const perk = miningPerkById[selected] ?? miningPerks[0]
  const state = getProfessionPerkPurchaseState(game.professions, perk, miningPerkById)
  return <section className="panel mining-perk-panel"><div className="panel-header"><div><div className="panel-title">Mining Perk Tree</div><div className="panel-subtitle">Choose across branches. Total cost: 124 points; Level 100 grants 99.</div></div><div className="mining-perk-accounting"><span>Levels {professionPointsFromLevels(game.professions, "mining")}</span><span>Bonus {game.professions.skills.mining?.bonusSkillPoints ?? 0}</span><span>Spent {professionPointsSpent(game.professions, "mining")}</span><strong>Available {professionAvailablePoints(game.professions, "mining")}</strong></div></div><div className="mining-perk-layout"><div className="mining-perk-grid">{miningPerks.map((entry) => { const entryState = getProfessionPerkPurchaseState(game.professions, entry, miningPerkById); return <button key={entry.id} className={"mining-perk-node is-" + entry.type + " " + (entry.id === selected ? "is-selected " : "") + (entryState.currentRank > 0 ? "is-purchased" : "")} onClick={() => setSelected(entry.id)} data-debug-kind="mining-perk-node" data-debug-perk-id={entry.id}><strong>{entry.name}</strong><small>R {entryState.currentRank}/{entry.maxRank}</small></button> })}</div><aside className="mining-perk-details"><span className="tiny-label">{perk.branch}</span><h3>{perk.name}</h3><p>{perk.description}</p><div className="mining-detail-list"><span>Rank</span><strong>{state.currentRank} / {perk.maxRank}</strong><span>Required Mining</span><strong>{perk.requiredSkillLevel}</strong><span>Cost</span><strong>{state.status === "maxed" ? "Complete" : "1 point / rank"}</strong><span>Status</span><strong>{state.status}</strong></div><button className="button button-primary full-button" disabled={state.status !== "available"} onClick={() => onPurchase(perk.id)}>{state.status === "available" ? "PURCHASE RANK " + (state.currentRank + 1) : state.status === "maxed" ? "MAX RANK" : state.status.replace("-", " ").toUpperCase()}</button></aside></div></section>
}

function MasteryPanel({ game, progress, rates }: { game: GameState; progress: ReturnType<typeof ironMasteryProgress>; rates: MiningRateEstimate }) {
  const level = ironMasteryLevel(game.professions.resourceMasteries["mastery.iron-vein"])
  return <section className="panel mining-mastery-panel"><div className="panel-header"><div><div className="panel-title">Iron Vein Mastery {level}</div><div className="panel-subtitle">Automatic progression from Iron swings. No mastery points.</div></div><span className="mining-points-badge">{formatRate(rates.masteryXpPerHour, 0)} XP / HOUR</span></div><div className="panel-body"><ProgressBar value={progress.progressFraction * 100} variant="experience" ariaLabel="Iron mastery experience" /><div className="mining-stat-grid"><Stat label="Mastery XP" value={Math.floor(game.professions.resourceMasteries["mastery.iron-vein"].totalXp).toLocaleString()} /><Stat label="XP to next" value={progress.isMaxLevel ? "MAX LEVEL" : Math.ceil(progress.xpToNextLevel).toLocaleString()} /><Stat label="ETA" value={progress.isMaxLevel ? "MAX LEVEL" : formatEta(progress.xpToNextLevel, rates.masteryXpPerHour)} /><Stat label="Passive" value={"+" + ((level - 1) * 0.1).toFixed(2) + "% Ore / +" + ((level - 1) * 0.05).toFixed(2) + "% Damage"} /></div><div className="mastery-timeline">{IRON_MASTERY_MILESTONES.map((milestone) => <div key={milestone.level} className={"mastery-milestone " + (level >= milestone.level ? "is-active" : "")}><strong>Lv {milestone.level}</strong><span>{milestone.name}</span><small>{milestone.description}</small></div>)}</div></div></section>
}

function Stat({ label, value }: { label: string; value: string }) { return <div className="mining-stat"><span>{label}</span><strong>{value}</strong></div> }
function formatRate(value: number, digits: number) { if (value <= 0) return "<0.01"; return value.toLocaleString(undefined, { maximumFractionDigits: digits, minimumFractionDigits: digits === 0 ? 0 : 2 }) }
function formatEta(xp: number, rate: number) { if (rate <= 0) return "-"; const seconds = Math.ceil(xp / rate * 3600); if (seconds < 60) return seconds + "s"; if (seconds < 3600) return Math.floor(seconds / 60) + "m " + seconds % 60 + "s"; return Math.floor(seconds / 3600) + "h " + Math.floor(seconds % 3600 / 60) + "m" }
