import { BookOpen, CircleHelp, Compass, Crosshair, Info, Map, Shield, Sparkles, Swords, Zap, type LucideIcon } from 'lucide-react'
import { combatReferenceGroups, combatStatReferences, damageTypeReferences } from '../../../game/data/combatGlossary'
import { effectDefinitions } from '../../../game/data/effects'
import { proficiencyDefinitions } from '../../../game/data/proficiencies'
import { proficiencyPerkDefinitions } from '../../../game/data/proficiencyPerks'
import { spellDefinitions } from '../../../game/data/spells'
import { stanceDefinitions } from '../../../game/data/stances'
import { techniqueDefinitions } from '../../../game/data/techniques'
import { CollapsiblePanel } from '../../components/CollapsiblePanel'
import { Panel } from '../../components/Panel'
import { ScreenHeading } from '../../shell/ScreenHeading'

export function InfoScreen() {
  return <div className="screen info-screen" data-debug-screen="info">
    <ScreenHeading screen="info" />
    <div className="info-layout">
      <Panel title="About CombatBound Idle" subtitle="The first playable gameplay vertical slice" icon={Info} panelId="infoAbout" screen="info" className="info-about"><div className="info-hero"><div className="info-mark">CB</div><div><h3>CombatBound Idle</h3><p>A tactical semi-idle combat RPG prototype.</p></div></div><p>Choose an enemy territory rather than a single monster. A Combat Location owns a population and continuously generates randomized groups while the Hunt is active.</p><div className="info-tags"><span>LOCATION HUNTING</span><span>MULTI-ENEMY COMBAT</span><span>REAL PROGRESSION</span></div></Panel>
      <Panel title="Combat Basics" subtitle="What happens during a Hunt" icon={Swords} panelId="infoBasics" screen="info" className="info-guide"><GuideRow icon={Swords} title="Continuous combat" copy="Combat advances continuously in real time. Normal attacks happen automatically using Attack Interval." /><GuideRow icon={Crosshair} title="One selected target" copy="The Hunter attacks one selected enemy at a time. Every living enemy keeps independent HP, timers, actions, effects, and rewards." /><GuideRow icon={Shield} title="Player decisions" copy="Equipment, weapon Proficiency, stance, sustained Techniques, magic, Healing Potion, and target selection shape the fight." /></Panel>
      <Panel title="Combat Resolution" subtitle="The current defensive order" icon={Crosshair} panelId="infoResolution" screen="info" className="info-resolution"><div className="resolution-flow">{['Accuracy vs Evasion', 'Dodge', 'Parry', 'Block', 'Damage / Crit', 'Armor', 'Resistance', 'Barrier', 'Health'].map((step, index) => <div className="resolution-step" key={step}><strong>{step}</strong>{index < 8 && <span>↓</span>}</div>)}</div><p className="info-callout">A failed Accuracy check Misses before Dodge, Parry, Block, Armor, or Resistance. Barriers absorb incoming mitigated damage before HP.</p></Panel>
      <Panel title="Combat Stats Reference" subtitle="Definitions shared with Equipment and tooltips" icon={Zap} panelId="infoStats" screen="info" className="info-reference-panel"><div className="info-stat-reference">{combatReferenceGroups.map((group) => <CollapsiblePanel key={group.id} title={group.label} panelId={`info-stats-${group.id}`} screen="info" defaultOpen={group.id === 'offense'}><div className="info-reference-list">{combatStatReferences.filter((reference) => reference.category === group.id).map((reference) => <div className="info-reference-row" key={reference.id} data-debug-kind="info-stat-reference" data-debug-stat-key={reference.id}><div><strong>{reference.label}</strong><p>{reference.shortDescription}</p></div>{reference.formula && <small>{reference.formula}</small>}</div>)}</div></CollapsiblePanel>)}</div></Panel>
      <Panel title="Damage Types & Resistances" subtitle="Typed mitigation and weaknesses" icon={Sparkles} panelId="infoDamageTypes" screen="info" className="info-guide"><div className="damage-type-grid">{damageTypeReferences.map((type) => <div className="damage-type-card" key={type.id}><strong>{type.label}</strong><p>{type.description}</p></div>)}</div><p className="info-callout">Positive Resistance reduces that damage type. Negative Resistance is a Weakness and increases damage taken. True Damage ignores Armor and normal Resistances.</p></Panel>
      <Panel title="Statuses & Effects" subtitle="Current effect definitions" icon={Shield} panelId="infoEffects" screen="info" className="info-guide"><div className="effect-reference-list">{effectDefinitions.map((effect) => <div className={`effect-reference-row effect-${effect.kind}`} key={effect.id} data-debug-kind="info-effect-reference" data-debug-effect-id={effect.id}><div><strong>{effect.name}</strong><span>{effect.kind.toUpperCase()} · {effect.tags.join(' · ')}</span></div><p>{effect.description}</p><small>{effect.durationSeconds === null ? 'No fixed duration' : `${effect.durationSeconds.toFixed(1)}s duration`} · {effect.stacking.mode.replace('-', ' ')}</small></div>)}</div></Panel>
      <Panel title="Combat Proficiencies" subtitle="Use equipped weapons and authored spells to improve their trees" icon={BookOpen} panelId="infoProficiencies" screen="info" className="info-guide"><div className="skill-reference-grid">{proficiencyDefinitions.map((proficiency) => <div className="skill-reference-card" key={proficiency.id} data-debug-kind="info-proficiency-reference" data-debug-proficiency-id={proficiency.id}><strong>{proficiency.name}</strong><p>{proficiency.description}</p><small>{proficiency.category.toUpperCase()} · Maximum Level {proficiency.maxLevel} · {proficiency.perkIds.length} Perks</small></div>)}</div></Panel>
      <Panel title="Combat Mastery & Perks" subtitle="Global progression earned from eligible weapon and magic outcomes" icon={Sparkles} panelId="infoMastery" screen="info" className="info-guide"><div className="skill-reference-grid"><div className="skill-reference-card"><strong>Combat Mastery</strong><p>Each point of eligible Proficiency XP also grants one point of global Mastery XP. Mastery Level gates world content and grants Perk Points, but does not automatically add combat stats.</p><small>Separate Mastery XP curve · Maximum Level 100</small></div><div className="skill-reference-card"><strong>Magic progression</strong><p>Fire Magic gains XP from effective Flame Blast damage and the authored Burn it creates. Warding Magic gains one XP per barrier absorption. Disruption Magic gains fixed XP from successful interrupts based on danger.</p><small>Failed casts, misses, and uncredited effects grant no magic XP</small></div><div className="skill-reference-card"><strong>Perk Points</strong><p>The first Perk Point costs 1,000 Mastery XP. Each additional point costs 500 more than the previous threshold. Points are derived from lifetime Mastery XP and spent in unlocked trees.</p><small>{proficiencyPerkDefinitions.length} authored perks</small></div></div></Panel>
      <CollapsiblePanel title="Stances / Techniques / Spells" subtitle="Current combat choices" icon={Sparkles} panelId="infoActions" screen="info" defaultOpen={false} className="info-actions-panel"><div className="info-action-columns"><div><h3>Stances</h3>{Object.values(stanceDefinitions).map((stance) => <GuideRow key={stance.id} title={stance.name} copy={stance.description} />)}</div><div><h3>Techniques</h3>{Object.values(techniqueDefinitions).map((technique) => <GuideRow key={technique.id} title={technique.name} copy={`${technique.description} Drains ${technique.staminaDrainPerSecond} Stamina/s.`} />)}</div><div><h3>Spells</h3>{spellDefinitions.map((spell) => <GuideRow key={spell.id} title={spell.name} copy={`${spell.description} Costs ${spell.manaCost} Mana; ${spell.cooldownSeconds}s cooldown. Proficiency: ${spell.magicProficiencyId}.`} />)}</div></div></CollapsiblePanel>
      <Panel title="World navigation" subtitle="The Combat Browser hierarchy" icon={Map} panelId="infoWorld" screen="info" className="info-guide"><GuideRow icon={Compass} title="Choose a territory" copy="Browse Continent → Region → Area → Combat Location. Parent selections filter the next layer and cascade safely." /><GuideRow icon={Map} title="Locations own populations" copy="A location shows possible enemy types and group-size range. That list is informational; it is not an individual monster picker." /><GuideRow icon={Swords} title="Start a Hunt" copy="Starting a location generates a weighted random group. After recovery, another group is generated automatically until you stop, die, or trigger the safety rule." /></Panel>
      <Panel title="UI Inspector" subtitle="Development-only interface aid" icon={CircleHelp} panelId="infoInspector" screen="info" className="info-inspector"><p>The UI Inspector identifies semantic interface targets for design and development without changing authored layout.</p><ol><li>Click <strong>Inspect UI</strong> in the top status bar.</li><li>Hover to see a yellow target highlight and pixel dimensions.</li><li>Check the source file and line for the inspected JSX element.</li><li>Left-click to copy a CombatBound UI reference instantly.</li><li>Press <kbd>Escape</kbd> or close the card to exit.</li></ol></Panel>
      <Panel title="Current MVP limitations" subtitle="Deliberately deferred" icon={BookOpen} panelId="infoPrototype" screen="info" className="info-status"><div className="status-checks"><span>✓ No offline combat simulation</span><span>✓ No crafting or gathering systems</span><span>✓ No movement, companions, or bosses</span><span>✓ Placeholder art and temporary balance</span></div></Panel>
    </div>
  </div>
}

function GuideRow({ icon: Icon, title, copy }: { icon?: LucideIcon; title: string; copy: string }) { return <div className="guide-row"><span className="guide-icon">{Icon ? <Icon size={15} /> : <span>•</span>}</span><div><strong>{title}</strong><p>{copy}</p></div></div> }
