import { BookOpen, CircleHelp, Compass, Crosshair, Info, Map, Shield, Sparkles, Swords, type LucideIcon } from 'lucide-react'
import { Panel } from '../../components/Panel'
import { ScreenHeading } from '../../shell/ScreenHeading'

export function InfoScreen() {
  return <div className="screen info-screen" data-debug-screen="info">
    <ScreenHeading screen="info" />
    <div className="info-layout">
      <Panel title="About CombatBound Idle" subtitle="The first playable gameplay vertical slice" icon={Info} panelId="infoAbout" screen="info" className="info-about"><div className="info-hero"><div className="info-mark">CB</div><div><h3>CombatBound Idle</h3><p>A tactical semi-idle combat RPG prototype.</p></div></div><p>Choose an enemy territory rather than a single monster. A Combat Location owns a family-specific population and continuously generates randomized groups while the Hunt is active.</p><div className="info-tags"><span>LOCATION HUNTING</span><span>MULTI-ENEMY COMBAT</span><span>REAL PROGRESSION</span></div></Panel>
      <Panel title="World navigation" subtitle="The Combat Browser hierarchy" icon={Map} panelId="infoWorld" screen="info" className="info-guide"><GuideRow icon={Compass} title="Choose a territory" copy="Browse Continent → Region → Area → Sub-area → Combat Location. Parent selections filter the next layer and cascade safely." /><GuideRow icon={Map} title="Locations own populations" copy="A Wolf Den or Bandit Camp shows possible enemy types and group-size range. That list is informational; it is not an individual monster picker." /><GuideRow icon={Swords} title="Start a Hunt" copy="Starting a location generates a weighted random group. After recovery, another group is generated automatically until you stop, die, or trigger the safety rule." /></Panel>
      <Panel title="How combat works" subtitle="The active group" icon={Crosshair} panelId="infoGuide" screen="info" className="info-guide"><GuideRow icon={Swords} title="Automatic attacks" copy="Normal weapon attacks use real timers. Click a living enemy to change the runtime target without resetting attack progress." /><GuideRow icon={Crosshair} title="Independent enemies" copy="Every generated enemy has independent HP, attack timers, specials, reward resolution, and defeat state." /><GuideRow icon={Shield} title="Recovery and defeat" copy="Recovery starts only after the whole group clears. Previous enemy rewards remain permanent if the Hunter later stops or dies." /></Panel>
      <Panel title="Tactical decisions" subtitle="Active play improves preparation" icon={Sparkles} panelId="infoCombat" screen="info" className="info-guide"><GuideRow icon={Shield} title="Stances and techniques" copy="High increases damage, Mid is balanced, and Low favors accuracy and defense. Sustained techniques drain Energy and shut down at zero." /><GuideRow icon={Sparkles} title="Spells and potion" copy="Spend Adrenaline on Flame Blast, Protective Sign, or Disrupting Pulse. Healing Potions can be used during active combat." /></Panel>
      <Panel title="UI Inspector" subtitle="Development-only interface aid" icon={CircleHelp} panelId="infoInspector" screen="info" className="info-inspector"><p>The UI Inspector identifies semantic interface targets for design and development without changing authored layout.</p><ol><li>Click <strong>Inspect UI</strong> in the top status bar.</li><li>Hover to see a yellow target highlight and pixel dimensions.</li><li>Check the source file and line for the inspected JSX element.</li><li>Left-click to copy a CombatBound UI reference instantly.</li><li>Press <kbd>Escape</kbd> or close the card to exit.</li></ol></Panel>
      <Panel title="Current MVP limitations" subtitle="Deliberately deferred" icon={BookOpen} panelId="infoPrototype" screen="info" className="info-status"><div className="status-checks"><span>✓ No offline combat simulation</span><span>✓ No crafting or gathering systems</span><span>✓ No movement, companions, or bosses</span><span>✓ Placeholder art and temporary balance</span></div></Panel>
    </div>
  </div>
}

function GuideRow({ icon: Icon, title, copy }: { icon: LucideIcon; title: string; copy: string }) { return <div className="guide-row"><span className="guide-icon"><Icon size={15} /></span><div><strong>{title}</strong><p>{copy}</p></div></div> }
