import { useMemo, useState } from "react";
import { proficiencyDefinitions } from "../../../../game/data/proficiencies";
import { perkById } from "../../../../game/data/proficiencyPerks";
import { calculateAvailablePerkPoints, calculateEarnedPerkPoints, calculateSpentPerkPoints, getMasteryLevelProgress } from "../../../../game/progression/masteryProgression";
import { getProficiencyLevelProgress } from "../../../../game/progression/proficiencyProgression";
import { MAX_MASTERY_LEVEL, MAX_PROFICIENCY_LEVEL } from "../../../../game/progression/progressionBalance";
import { buildProficiencyTooltip } from "../../../../game/presentation/tooltipBuilders";
import type { ProficiencyCategory } from "../../../../game/progression/progressionTypes";
import type { CombatProficiencyId } from "../../../../game/progression/progressionTypes";
import { DebugButton } from "../components/DebugButton";
import { DebugCatalogueGroup } from "../components/DebugCatalogueGroup";
import { DebugCatalogueIdentity } from "../components/DebugCatalogueIdentity";
import { DebugSection } from "../components/DebugSection";
import type { DebugTabProps } from "../debugTypes";

const proficiencyCategories: Array<{ id: ProficiencyCategory; label: string }> = [{ id: "melee", label: "Melee" }, { id: "ranged", label: "Ranged" }, { id: "magic", label: "Magic" }, { id: "defense", label: "Defense" }];

export function DebugProgressionTab({ game, debug, run }: DebugTabProps) {
  const [search, setSearch] = useState("");
  const [expanded, setExpanded] = useState<Set<string>>(() => new Set(["debug.proficiencies.melee"]));
  const [customPoints, setCustomPoints] = useState("");
  const progress = getMasteryLevelProgress(game.progression.masteryXp);
  const query = search.trim().toLowerCase();
  const grouped = useMemo(() => proficiencyCategories.map((category) => ({ ...category, definitions: proficiencyDefinitions.filter((definition) => definition.category === category.id && `${definition.id} ${definition.name} ${definition.category} ${definition.description}`.toLowerCase().includes(query)) })).filter((category) => category.definitions.length > 0), [query]);
  const grant = (amount: number) => run(`Granted ${amount} derived perk points.`, () => debug.grantPerkPoints(amount));
  const customAmount = Number(customPoints);
  return <div className="debug-tab-content debug-column">
    <DebugSection title="Mastery" subtitle={`Level ${progress.level} - ${game.progression.masteryXp.toLocaleString()} XP - ${progress.xpToNextLevel.toLocaleString()} XP to next`}><div className="debug-button-grid"><DebugButton action="mastery-lv-1" onClick={() => run("Set Mastery to level 1.", () => debug.setMasteryLevel(1))}>LV 1</DebugButton><DebugButton action="mastery-lv-5" onClick={() => run("Set Mastery to level 5.", () => debug.setMasteryLevel(5))}>LV 5</DebugButton><DebugButton action="mastery-lv-10" onClick={() => run("Set Mastery to level 10.", () => debug.setMasteryLevel(10))}>LV 10</DebugButton><DebugButton action="mastery-lv-25" onClick={() => run("Set Mastery to level 25.", () => debug.setMasteryLevel(25))}>LV 25</DebugButton><DebugButton action="mastery-lv-50" onClick={() => run("Set Mastery to level 50.", () => debug.setMasteryLevel(50))}>LV 50</DebugButton><DebugButton action="mastery-max" onClick={() => run(`Set Mastery to level ${MAX_MASTERY_LEVEL}.`, () => debug.setMasteryLevel(MAX_MASTERY_LEVEL))}>MAX</DebugButton></div><div className="debug-button-row"><DebugButton action="add-mastery-xp" onClick={() => run("Added 100 Mastery XP.", () => debug.addMasteryXp(100))}>+100 XP</DebugButton><DebugButton action="add-mastery-xp" onClick={() => run("Added 1,000 Mastery XP.", () => debug.addMasteryXp(1000))}>+1,000 XP</DebugButton><DebugButton action="add-mastery-xp" onClick={() => run("Added 10,000 Mastery XP.", () => debug.addMasteryXp(10000))}>+10,000 XP</DebugButton></div></DebugSection>
    <DebugSection title="Perk Points" subtitle="Derived from Mastery XP; purchased perks remain unchanged."><div className="debug-summary-grid debug-perk-summary"><div className="debug-summary-card"><span>Earned</span><strong>{calculateEarnedPerkPoints(game.progression.masteryXp)}</strong></div><div className="debug-summary-card"><span>Spent</span><strong>{calculateSpentPerkPoints(game.progression, perkById)}</strong></div><div className="debug-summary-card"><span>Available</span><strong>{calculateAvailablePerkPoints(game.progression, perkById)}</strong></div></div><div className="debug-button-row"><DebugButton action="grant-perk-points-1" onClick={() => grant(1)}>+1</DebugButton><DebugButton action="grant-perk-points-5" onClick={() => grant(5)}>+5</DebugButton><DebugButton action="grant-perk-points-10" onClick={() => grant(10)}>+10</DebugButton><DebugButton action="grant-perk-points-25" onClick={() => grant(25)}>+25</DebugButton><label className="debug-custom-control">CUSTOM AMOUNT <input value={customPoints} onChange={(event) => setCustomPoints(event.target.value)} min="1" step="1" inputMode="numeric" aria-label="Custom perk point amount" /><DebugButton action="grant-custom-perk-points" onClick={() => Number.isInteger(customAmount) && customAmount > 0 ? grant(customAmount) : run("Enter a positive whole-number perk point amount.", () => undefined)}>GRANT</DebugButton></label></div></DebugSection>
    <DebugSection title="Proficiencies" subtitle="Direct setters change only proficiency XP; Mastery XP stays isolated." actions={<input className="debug-search-input" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search proficiencies..." aria-label="Search proficiencies" data-debug-kind="debug-proficiency-search" />}><div className="debug-button-row"><DebugButton action="set-all-proficiencies-lv-1" onClick={() => run("Set all proficiencies to level 1.", () => debug.setAllProficiencyLevels(1))}>ALL LV 1</DebugButton><DebugButton action="set-all-proficiencies-lv-10" onClick={() => run("Set all proficiencies to level 10.", () => debug.setAllProficiencyLevels(10))}>ALL LV 10</DebugButton><DebugButton action="set-all-proficiencies-max" onClick={() => run(`Set all proficiencies to level ${MAX_PROFICIENCY_LEVEL}.`, () => debug.setAllProficiencyLevels(MAX_PROFICIENCY_LEVEL))}>ALL MAX</DebugButton><DebugButton action="reset-all-proficiencies" onClick={() => run("Reset all proficiencies to level 0.", () => debug.setAllProficiencyLevels(0))}>RESET ALL</DebugButton><DebugButton action="discover-all-proficiencies" onClick={() => run("Discovered all proficiencies.", debug.discoverAllProficiencies)}>DISCOVER ALL</DebugButton></div><div className="debug-catalogue">{grouped.map((category) => { const id = `debug.proficiencies.${category.id}`; const isOpen = query ? true : expanded.has(id); return <DebugCatalogueGroup key={id} id={id} label={category.label} count={category.definitions.length} icon={category.id === "melee" ? "sword" : category.id === "ranged" ? "bow" : category.id === "magic" ? "spark" : "shield"} expanded={isOpen} onToggle={() => setExpanded((current) => { const next = new Set(current); if (next.has(id)) next.delete(id); else next.add(id); return next; })} debugGroupType="proficiency">{category.definitions.map((definition) => <DebugProficiencyRow key={definition.id} definition={definition} game={game} run={run} debug={debug} />)}</DebugCatalogueGroup>; })}</div></DebugSection>
  </div>;
}

function DebugProficiencyRow({ definition, game, run, debug }: { definition: (typeof proficiencyDefinitions)[number]; game: DebugTabProps["game"]; run: DebugTabProps["run"]; debug: DebugTabProps["debug"] }) {
  const [level, setLevel] = useState(String(getProficiencyLevelProgress(game.progression.proficiencies[definition.id]?.totalXp ?? 0, definition.maxLevel).level));
  const current = getProficiencyLevelProgress(game.progression.proficiencies[definition.id]?.totalXp ?? 0, definition.maxLevel);
  return <div className="debug-catalogue-row" data-debug-kind="debug-proficiency" data-debug-proficiency-id={definition.id}><DebugCatalogueIdentity tooltip={buildProficiencyTooltip(definition)} icon={definition.icon} kind="debug-proficiency-identity" targetId={definition.id} label={definition.name}><strong>{definition.name}</strong><small>{definition.category} - Lv {current.level} - {(game.progression.proficiencies[definition.id]?.totalXp ?? 0).toLocaleString()} XP</small></DebugCatalogueIdentity><input value={level} onChange={(event) => setLevel(event.target.value)} aria-label={`Set ${definition.name} level`} inputMode="numeric" /><button type="button" onClick={() => run(`Set ${definition.name} to level ${level}.`, () => debug.setProficiencyLevel(definition.id as CombatProficiencyId, Number(level)))} data-debug-kind="debug-action" data-debug-action="set-proficiency-level" data-debug-proficiency-id={definition.id}>SET</button><button type="button" onClick={() => run(`Increased ${definition.name} by one level.`, () => debug.setProficiencyLevel(definition.id as CombatProficiencyId, current.level + 1))} data-debug-kind="debug-action" data-debug-action="increment-proficiency" data-debug-proficiency-id={definition.id}>+1</button></div>;
}
