import { useGameStore } from "../../../../state/gameStore";
import { getBlacksmithingStats } from "../../../../game/professions/blacksmithing/blacksmithingStats";
import { blacksmithingRecipes } from "../../../../game/professions/blacksmithing/blacksmithingRecipes";
import { DebugSection } from "../components/DebugSection";
import { DebugButton } from "../components/DebugButton";
import type { DebugTabProps } from "../debugTypes";

export function DebugBlacksmithingTab({ debug, run }: DebugTabProps) {
  const game = useGameStore((state) => state.game);
  const startBlacksmithing = useGameStore((state) => state.startBlacksmithing);
  const stats = getBlacksmithingStats(game);
  const operation = game.blacksmithing.activeOperation;
  return <div className="debug-tab-content debug-column">
    <DebugSection title="Blacksmithing progression" subtitle="Level, XP and the shared profession perk-point system."><div className="debug-button-row"><DebugButton action="blacksmithing-level-1" onClick={() => run("Set Blacksmithing to level 1.", () => debug.setBlacksmithingLevel(1))}>LEVEL 1</DebugButton><DebugButton action="blacksmithing-level-10" onClick={() => run("Set Blacksmithing to level 10.", () => debug.setBlacksmithingLevel(10))}>LEVEL 10</DebugButton><DebugButton action="blacksmithing-level-50" onClick={() => run("Set Blacksmithing to level 50.", () => debug.setBlacksmithingLevel(50))}>LEVEL 50</DebugButton><DebugButton action="blacksmithing-level-100" onClick={() => run("Set Blacksmithing to level 100.", () => debug.setBlacksmithingLevel(100))}>LEVEL 100</DebugButton><DebugButton action="blacksmithing-set-xp" onClick={() => run("Set Blacksmithing XP to 1,000.", () => debug.setBlacksmithingXp(1000))}>SET XP 1000</DebugButton><DebugButton action="blacksmithing-add-point" onClick={() => run("Added one Blacksmithing skill point.", debug.addBlacksmithingSkillPoint)}>ADD BONUS POINT</DebugButton><DebugButton action="blacksmithing-reset-perks" danger onClick={() => run("Reset Blacksmithing perks.", debug.resetBlacksmithingPerks)}>RESET PERKS</DebugButton></div><div className="debug-button-row"><DebugButton action="blacksmithing-add-level" onClick={() => run("Added one Blacksmithing level.", () => debug.addBlacksmithingLevel(1))}>+1 LEVEL</DebugButton><DebugButton action="blacksmithing-add-10-levels" onClick={() => run("Added 10 Blacksmithing levels.", () => debug.addBlacksmithingLevel(10))}>+10 LEVELS</DebugButton><DebugButton action="blacksmithing-reset-bonus" onClick={() => run("Reset Blacksmithing bonus points.", debug.resetBlacksmithingBonusPoints)}>RESET BONUS</DebugButton></div></DebugSection>
    <DebugSection title="Forge" subtitle="Forge Stamina and rest use the production runtime."><div className="debug-button-row"><DebugButton action="forge-full" onClick={() => run("Set Forge Stamina to full.", () => debug.setForgeStamina(stats.maxForgeStamina))}>SET FULL</DebugButton><DebugButton action="forge-50" onClick={() => run("Set Forge Stamina to 50.", () => debug.setForgeStamina(50))}>SET 50</DebugButton><DebugButton action="forge-1" onClick={() => run("Set Forge Stamina to 1.", () => debug.setForgeStamina(1))}>SET 1</DebugButton><DebugButton action="forge-0" onClick={() => run("Set Forge Stamina to 0.", () => debug.setForgeStamina(0))}>SET 0</DebugButton><DebugButton action="forge-rest" onClick={() => run("Forced Forge rest.", debug.forceForgeRest)}>FORCE REST</DebugButton><DebugButton action="forge-complete-rest" onClick={() => run("Completed Forge rest.", debug.completeForgeRest)}>COMPLETE REST</DebugButton></div><div className="debug-validation-list"><div><strong>MODE</strong><span>{game.blacksmithing.mode} - {game.blacksmithing.activityKind ?? "none"}</span></div><div><strong>STAMINA</strong><span>{game.blacksmithing.forgeStamina.toFixed(1)} / {stats.maxForgeStamina}</span></div><div><strong>OPERATION</strong><span>{operation?.kind ?? "none"} - {operation ? game.blacksmithing.actionTimerRemaining.toFixed(1) + "s" : "idle"}</span></div></div></DebugSection>
    <DebugSection title="Materials and recipes" subtitle="The authored V1 catalogue is data-driven: one Smelting recipe and fourteen Smithing recipes."><div className="debug-button-row"><DebugButton action="grant-iron-ore" onClick={() => run("Granted 100 Iron Ore.", () => debug.grantBlacksmithingMaterials("item.iron-ore", 100))}>GRANT 100 IRON ORE</DebugButton><DebugButton action="grant-iron-bars" onClick={() => run("Granted 100 Iron Bars.", () => debug.grantBlacksmithingMaterials("item.iron-bar", 100))}>GRANT 100 IRON BARS</DebugButton>{blacksmithingRecipes.map((recipe) => <DebugButton key={recipe.id + "-materials"} action={recipe.id + "-materials"} onClick={() => run("Granted " + recipe.name + " materials.", () => debug.grantBlacksmithingMaterials(recipe.costs[0].itemId, recipe.costs[0].quantity))}>GRANT {recipe.name.toUpperCase()} MATERIALS</DebugButton>)}</div><div className="debug-validation-list"><div><strong>START x1</strong><span>{blacksmithingRecipes.map((recipe) => <button key={recipe.id + "-start-1"} className="button button-ghost" onClick={() => run("Started " + recipe.name + " x1.", () => startBlacksmithing(recipe.id, 1, "fixed"))}>{recipe.name}</button>)}</span></div><div><strong>START x5</strong><span>{blacksmithingRecipes.map((recipe) => <button key={recipe.id + "-start-5"} className="button button-ghost" onClick={() => run("Started " + recipe.name + " x5.", () => startBlacksmithing(recipe.id, 5, "fixed"))}>{recipe.name}</button>)}</span></div><div><strong>START MAX</strong><span>{blacksmithingRecipes.map((recipe) => <button key={recipe.id + "-start-max"} className="button button-ghost" onClick={() => run("Started " + recipe.name + " MAX.", () => startBlacksmithing(recipe.id, 1, "max"))}>{recipe.name}</button>)}</span></div></div></DebugSection>
    <DebugSection title="Canonical time advance" subtitle="All buttons use the same event-boundary simulator as live activity and Time Bank."><div className="debug-button-row">{[1, 10, 60, 3600].map((seconds) => <DebugButton key={seconds} action={"blacksmithing-advance-" + seconds} onClick={() => run("Advanced Blacksmithing by " + seconds + " seconds.", () => debug.advanceBlacksmithingTime(seconds))}>{seconds === 3600 ? "1 HOUR" : seconds + "s"}</DebugButton>)}</div></DebugSection>
  </div>;
}
