import type { InventoryAvailabilityFilter, InventoryFilters, InventoryModificationFilter, InventoryPrimaryCategory } from "../../../game/inventory/inventorySelectors";

export function InventoryFiltersPopover({ id, category, filters, setFilters, showEquipmentState: showEquipmentStateOverride }: { id: string; category: InventoryPrimaryCategory; filters: InventoryFilters; setFilters: (filters: InventoryFilters) => void; showEquipmentState?: boolean }) {
  const showEquipmentState = showEquipmentStateOverride ?? (category === "all" || category === "equipment");
  const showEquipmentFilters = category === "all" || category === "equipment";
  return <div id={id} className="inventory-filter-popover" data-debug-kind="inventory-filter-popover">
    <label title="Filter items by Common, Uncommon, or Rare.">Rarity<select aria-label="Rarity" value={filters.rarity} onChange={(event) => setFilters({ ...filters, rarity: event.target.value as InventoryFilters["rarity"] })}><option value="all">All rarities</option><option value="common">Common</option><option value="uncommon">Uncommon</option><option value="rare">Rare</option></select></label>
    {showEquipmentState && <label title="Limit results to equipped or unequipped equipment.">Equipment state<select aria-label="Equipment state" value={filters.equipmentState} onChange={(event) => setFilters({ ...filters, equipmentState: event.target.value as InventoryFilters["equipmentState"] })}><option value="all">All equipment</option><option value="equipped">Equipped</option><option value="unequipped">Unequipped</option></select></label>}
    {showEquipmentFilters && <label title="Choose whether equipment has any modification, Affixes, Upgrades, or Quality.">Modification<select aria-label="Modification" value={filters.modification} onChange={(event) => setFilters({ ...filters, modification: event.target.value as InventoryModificationFilter })}><option value="all">Modified or unmodified</option><option value="modified">Has any modifications</option><option value="unmodified">No modifications</option><option value="affixed">Has Affixes</option><option value="upgraded">Upgraded</option><option value="quality">Quality Improved</option></select></label>}
    {showEquipmentFilters && <label title="Can Equip Now means the Hunter Rank requirement is met and the item has a valid equipment target.">Availability<select aria-label="Availability" value={filters.availability ?? "all"} onChange={(event) => setFilters({ ...filters, availability: event.target.value as InventoryAvailabilityFilter })}><option value="all">All availability</option><option value="usable">Can equip now</option><option value="locked">Hunter Rank locked</option></select></label>}
  </div>;
}
