import type { ProfessionPerkDefinition, ProfessionPerkPrerequisite } from "../professionPerkTypes"
import type { BlacksmithingModifier, BlacksmithingRecipeTag } from "./blacksmithingTypes"

const all = (...requirements: [string, number][]): ProfessionPerkPrerequisite[] => requirements.length ? [{ mode: "all", requirements: requirements.map(([perkId, requiredRank]) => ({ perkId, requiredRank })) }] : []
const any = (minimumSatisfied: number, ...perkIds: string[]): ProfessionPerkPrerequisite[] => [{ mode: "any", minimumSatisfied, requirements: perkIds.map((perkId) => ({ perkId, requiredRank: 1 })) }]
const perk = (id: string, name: string, branch: string, type: ProfessionPerkDefinition["type"], maxRank: number, requiredSkillLevel: number, description: string, effects: ProfessionPerkDefinition["effects"], prerequisiteRules: ProfessionPerkPrerequisite[] = [], x = 0, y = 0): ProfessionPerkDefinition => ({ id, skillId: "blacksmithing", name, branch, type, maxRank, costPerRank: 1, requiredSkillLevel, description, effects, prerequisiteRules, position: { x, y } })
const e = (modifier: BlacksmithingModifier, valuePerRank: number, recipeTags?: BlacksmithingRecipeTag[]) => ({ type: "blacksmithingModifier" as const, modifier, valuePerRank, recipeTags })

export const blacksmithingPerks: ProfessionPerkDefinition[] = [
  // Core
  perk("blacksmithing-perk.forge-foundation", "Forge Foundation", "Core / Foundation", "small", 1, 2, "+5 Max Forge Stamina", [e("maxForgeStaminaFlat", 5)], [], 50, 0),
  perk("blacksmithing-perk.smiths-discipline", "Smith's Discipline", "Core / Foundation", "small", 5, 1, "+3% Blacksmithing XP per rank", [e("blacksmithingXpIncreased", 0.03)], all(["blacksmithing-perk.forge-foundation", 1]), 30, 1),
  perk("blacksmithing-perk.steady-hands", "Steady Hands", "Core / Foundation", "small", 4, 1, "+1.5% all operation speed per rank", [e("allOperationSpeedIncreased", 0.015)], all(["blacksmithing-perk.forge-foundation", 1]), 70, 1),
  perk("blacksmithing-perk.enduring-forge", "Enduring Forge", "Core / Foundation", "small", 5, 1, "+5 Max Forge Stamina per rank", [e("maxForgeStaminaFlat", 5)], all(["blacksmithing-perk.forge-foundation", 1]), 50, 2),
  perk("blacksmithing-perk.tempered-focus", "Tempered Focus", "Core / Foundation", "small", 5, 1, "-2% Forge Stamina cost per rank", [e("forgeStaminaCostReduced", 0.02)], all(["blacksmithing-perk.enduring-forge", 2]), 50, 3),
  perk("blacksmithing-perk.veteran-blacksmith", "Veteran Blacksmith", "Core / Foundation", "notable", 1, 35, "+10% Blacksmithing XP and +5% all operation speed", [e("blacksmithingXpIncreased", 0.10), e("allOperationSpeedIncreased", 0.05)], all(["blacksmithing-perk.smiths-discipline", 5], ["blacksmithing-perk.steady-hands", 4]), 50, 5),

  // Forgemaster
  perk("blacksmithing-perk.bellows-mastery", "Bellows Mastery", "Forgemaster", "small", 5, 1, "+3% Smelting speed per rank", [e("smeltingSpeedIncreased", 0.03, ["smelting"])], all(["blacksmithing-perk.steady-hands", 2]), 10, 7),
  perk("blacksmithing-perk.heat-control", "Heat Control", "Forgemaster", "small", 5, 1, "-3% Smelting Forge Stamina cost per rank", [e("smeltingStaminaCostReduced", 0.03, ["smelting"])], all(["blacksmithing-perk.enduring-forge", 2]), 30, 7),
  perk("blacksmithing-perk.furnace-rhythm", "Furnace Rhythm", "Forgemaster", "small", 5, 1, "+3% Smelting XP per rank", [e("smeltingXpIncreased", 0.03, ["smelting"])], all(["blacksmithing-perk.bellows-mastery", 2]), 10, 8),
  perk("blacksmithing-perk.forge-recovery-drill", "Recovery Drill", "Forgemaster", "small", 5, 1, "-4% Forge Rest Duration per rank", [e("forgeRestDurationReduced", 0.04)], all(["blacksmithing-perk.heat-control", 3]), 30, 8),
  perk("blacksmithing-perk.smelters-eye", "Smelter's Eye", "Forgemaster", "small", 4, 1, "+2% chance to recover 1 Iron Ore after Smelting per rank", [e("smeltingBaseMaterialRecoveryChance", 0.02, ["smelting"])], all(["blacksmithing-perk.bellows-mastery", 3], ["blacksmithing-perk.furnace-rhythm", 2]), 10, 9),
  perk("blacksmithing-perk.overheated-forge", "Overheated Forge", "Forgemaster", "keystone", 1, 30, "+20% Smelting speed, +15% Smelting Forge Stamina cost", [e("smeltingSpeedIncreased", 0.20, ["smelting"]), e("smeltingStaminaCostReduced", -0.15, ["smelting"])], all(["blacksmithing-perk.bellows-mastery", 5], ["blacksmithing-perk.heat-control", 3]), 10, 11),
  perk("blacksmithing-perk.master-forgemaster", "Master Forgemaster", "Forgemaster", "notable", 1, 50, "+10% Smelting speed and +5% Smelting material recovery", [e("smeltingSpeedIncreased", 0.10, ["smelting"]), e("smeltingBaseMaterialRecoveryChance", 0.05, ["smelting"])], all(["blacksmithing-perk.furnace-rhythm", 5], ["blacksmithing-perk.forge-recovery-drill", 5], ["blacksmithing-perk.smelters-eye", 4]), 10, 13),

  // Weaponsmith
  perk("blacksmithing-perk.weapon-rhythm", "Weapon Rhythm", "Weaponsmith", "small", 5, 1, "+3% Weapon Smithing speed per rank", [e("weaponSmithingSpeedIncreased", 0.03, ["weapon"])], all(["blacksmithing-perk.steady-hands", 2]), 50, 7),
  perk("blacksmithing-perk.weapon-recovery", "Weapon Recovery", "Weaponsmith", "small", 5, 1, "+2% chance to recover 1 Iron Bar after Weapon Smithing per rank", [e("weaponBaseMaterialRecoveryChance", 0.02, ["weapon"])], all(["blacksmithing-perk.weapon-rhythm", 2]), 50, 8),
  perk("blacksmithing-perk.weapon-upgrade-practice", "Weapon Forging Practice", "Weaponsmith", "small", 5, 1, "+2% Weapon Smithing speed per rank", [e("weaponSmithingSpeedIncreased", 0.02, ["weapon"])], all(["blacksmithing-perk.weapon-rhythm", 3]), 70, 8),
  perk("blacksmithing-perk.balanced-edge", "Balanced Edge", "Weaponsmith", "small", 4, 1, "+3% Blacksmithing XP from Weapon Smithing per rank", [e("weaponSmithingXpIncreased", 0.03, ["weapon"])], all(["blacksmithing-perk.weapon-recovery", 2]), 50, 9),
  perk("blacksmithing-perk.heavy-weapon-handling", "Heavy Weapon Handling", "Weaponsmith", "small", 4, 1, "-3% Forge Stamina cost for Weapon Smithing per rank", [e("weaponSmithingStaminaCostReduced", 0.03, ["weapon"])], all(["blacksmithing-perk.weapon-upgrade-practice", 2]), 70, 9),
  perk("blacksmithing-perk.blade-specialist", "Blade Specialist", "Weaponsmith", "keystone", 1, 40, "+25% Weapon Smithing speed, -10% Defensive Smithing speed", [e("weaponSmithingSpeedIncreased", 0.25, ["weapon"]), e("defensiveSmithingSpeedIncreased", -0.10, ["defensive"])], all(["blacksmithing-perk.weapon-rhythm", 5], ["blacksmithing-perk.weapon-upgrade-practice", 5]), 70, 11),
  perk("blacksmithing-perk.master-weaponsmith", "Master Weaponsmith", "Weaponsmith", "notable", 1, 55, "+10% Weapon Smithing speed and +10% XP from Weapon Smithing", [e("weaponSmithingSpeedIncreased", 0.10, ["weapon"]), e("weaponSmithingXpIncreased", 0.10, ["weapon"])], all(["blacksmithing-perk.weapon-recovery", 5], ["blacksmithing-perk.balanced-edge", 4], ["blacksmithing-perk.heavy-weapon-handling", 4]), 70, 13),

  // Armorer
  perk("blacksmithing-perk.armorer-rhythm", "Armorer Rhythm", "Armorer", "small", 5, 1, "+3% Defensive Smithing speed per rank", [e("defensiveSmithingSpeedIncreased", 0.03, ["defensive"])], all(["blacksmithing-perk.steady-hands", 2]), 90, 7),
  perk("blacksmithing-perk.armorer-recovery", "Armorer Recovery", "Armorer", "small", 5, 1, "+2% chance to recover 1 Iron Bar after Defensive Smithing per rank", [e("defensiveBaseMaterialRecoveryChance", 0.02, ["defensive"])], all(["blacksmithing-perk.armorer-rhythm", 2]), 90, 8),
  perk("blacksmithing-perk.defensive-upgrade-practice", "Armor Forging Practice", "Armorer", "small", 5, 1, "+2% Defensive Smithing speed per rank", [e("defensiveSmithingSpeedIncreased", 0.02, ["defensive"])], all(["blacksmithing-perk.armorer-rhythm", 3]), 90, 9),
  perk("blacksmithing-perk.reinforced-workflow", "Reinforced Workflow", "Armorer", "small", 4, 1, "+3% Blacksmithing XP from Defensive Smithing per rank", [e("defensiveSmithingXpIncreased", 0.03, ["defensive"])], all(["blacksmithing-perk.armorer-recovery", 2]), 90, 10),
  perk("blacksmithing-perk.shieldcraft", "Shieldcraft", "Armorer", "small", 4, 1, "-3% Forge Stamina cost for Defensive Smithing per rank", [e("defensiveSmithingStaminaCostReduced", 0.03, ["defensive"])], all(["blacksmithing-perk.defensive-upgrade-practice", 2]), 90, 11),
  perk("blacksmithing-perk.armorer-specialist", "Armorer Specialist", "Armorer", "keystone", 1, 40, "+25% Defensive Smithing speed, -10% Weapon Smithing speed", [e("defensiveSmithingSpeedIncreased", 0.25, ["defensive"]), e("weaponSmithingSpeedIncreased", -0.10, ["weapon"])], all(["blacksmithing-perk.armorer-rhythm", 5], ["blacksmithing-perk.defensive-upgrade-practice", 5]), 90, 12),
  perk("blacksmithing-perk.master-armorer", "Master Armorer", "Armorer", "notable", 1, 55, "+10% Defensive Smithing speed and +10% XP from Defensive Smithing", [e("defensiveSmithingSpeedIncreased", 0.10, ["defensive"]), e("defensiveSmithingXpIncreased", 0.10, ["defensive"])], all(["blacksmithing-perk.armorer-recovery", 5], ["blacksmithing-perk.reinforced-workflow", 4], ["blacksmithing-perk.shieldcraft", 4]), 90, 14),

  // Cross / general
  perk("blacksmithing-perk.toolsmith", "Toolsmith", "Cross / General", "small", 4, 8, "+4% Tool Smithing speed per rank", [e("toolSmithingSpeedIncreased", 0.04, ["tool"])], all(["blacksmithing-perk.steady-hands", 2]), 50, 16),
  perk("blacksmithing-perk.iron-economy", "Iron Economy", "Cross / General", "small", 5, 12, "+1.5% global base-metal recovery chance per rank", [e("globalBaseMaterialRecoveryChance", 0.015, ["iron"])], all(["blacksmithing-perk.smelters-eye", 2]), 20, 16),
  perk("blacksmithing-perk.upgrade-focus", "Forge Efficiency", "Cross / General", "small", 5, 15, "-2% Forge Stamina cost per rank", [e("forgeStaminaCostReduced", 0.02)], all(["blacksmithing-perk.smiths-discipline", 3]), 80, 16),
  perk("blacksmithing-perk.production-savant", "Production Savant", "Cross / General", "small", 4, 25, "+2% Smelting speed and +2% Smithing speed per rank", [e("smeltingSpeedIncreased", 0.02, ["smelting"]), e("smithingSpeedIncreased", 0.02, ["iron"])], all(["blacksmithing-perk.bellows-mastery", 3], ["blacksmithing-perk.weapon-rhythm", 2], ["blacksmithing-perk.armorer-rhythm", 2]), 50, 18),
  perk("blacksmithing-perk.efficient-artisan", "Efficient Artisan", "Cross / General", "keystone", 1, 50, "+15% global base-metal recovery chance, -10% all operation speed", [e("globalBaseMaterialRecoveryChance", 0.15, ["iron"]), e("allOperationSpeedIncreased", -0.10)], all(["blacksmithing-perk.iron-economy", 5], ["blacksmithing-perk.tempered-focus", 5]), 20, 20),
  perk("blacksmithing-perk.master-of-the-forge", "Master of the Forge", "Cross / General", "major", 1, 75, "+8% all operation speed, -8% Forge Stamina cost, +10% Blacksmithing XP", [e("allOperationSpeedIncreased", 0.08), e("forgeStaminaCostReduced", 0.08), e("blacksmithingXpIncreased", 0.10)], any(3, "blacksmithing-perk.veteran-blacksmith", "blacksmithing-perk.master-forgemaster", "blacksmithing-perk.master-weaponsmith", "blacksmithing-perk.master-armorer", "blacksmithing-perk.efficient-artisan"), 50, 22),
]

export const blacksmithingPerkById = Object.fromEntries(blacksmithingPerks.map((entry) => [entry.id, entry])) as Record<string, ProfessionPerkDefinition>
export const BLACKSMITHING_PERK_TREE_COST = blacksmithingPerks.reduce((sum, entry) => sum + entry.maxRank, 0)

if (BLACKSMITHING_PERK_TREE_COST <= 99) throw new Error("Blacksmithing perk tree must cost more than 99 points")
