import { Sparkles, Target } from 'lucide-react'
import { enemyById } from '../../../../game/data/enemies'
import { itemById } from '../../../../game/data/items'
import type { EnemyCombatInstance } from '../../../../game/combat/combatTypes'
import type { GameState } from '../../../../game/gameState'
import { Panel } from '../../../components/Panel'
import { PlaceholderArt } from '../../../components/PlaceholderArt'
import { ProgressBar } from '../../../components/ProgressBar'
import { formatPercent, combatProgress } from './combatUi'

export function SelectedEnemyPanel({ game, selectedEnemy }: { game: GameState; selectedEnemy?: EnemyCombatInstance }) {
  const combat = game.combat
  const definition = selectedEnemy ? enemyById[selectedEnemy.enemyId] : undefined
  return <Panel title="Selected enemy" subtitle="Current runtime target" icon={Target} panelId="targetCombat" screen="combat" className="target-combat-panel">
    {selectedEnemy && definition ? <><div className="target-card-top"><PlaceholderArt icon={definition.icon} label={selectedEnemy.displayName} size="medium" variant={definition.accent} /><div><h3>{selectedEnemy.displayName}</h3><p>{definition.family} · Group {combat.groupNumber}</p><span className="level-badge">{selectedEnemy.defeated ? 'DEFEATED' : `INSTANCE ${selectedEnemy.instanceId.split('#')[1]}`}</span></div></div><div className="target-health"><div><span>HEALTH</span><strong>{Math.floor(selectedEnemy.currentHealth)} / {selectedEnemy.maxHealth}</strong></div><ProgressBar value={(selectedEnemy.currentHealth / selectedEnemy.maxHealth) * 100} variant="health" /></div><div className="target-stat-grid"><TargetStat label="Attack" value={definition.attack} /><TargetStat label="Accuracy" value={definition.accuracy} /><TargetStat label="Defense" value={definition.defense} /><TargetStat label="Interval" value={`${definition.attackInterval.toFixed(1)}s`} /><TargetStat label="Dodge" value={formatPercent(definition.dodge)} /><TargetStat label="XP" value={definition.baseXp} /></div>{definition.parry > 0 || definition.block > 0 ? <div className="target-defenses"><span>Parry {formatPercent(definition.parry)}</span><span>Block {formatPercent(definition.block)}</span></div> : null}<div className="trait-section"><span className="tiny-label">TRAITS</span>{definition.traits.map((trait) => <div className="trait-row" key={trait.id}><strong>{trait.name}</strong><small>{trait.description}</small></div>)}</div>{definition.actions.length > 0 && <div className="enemy-actions-detail"><span className="tiny-label">SPECIAL ACTIONS</span>{definition.actions.map((action) => { const current = selectedEnemy.currentAction?.actionId === action.id; return <div className={`enemy-action-detail ${current ? `is-casting danger-${action.danger}` : ''}`} key={action.id}><strong>{current ? 'CASTING · ' : ''}{action.name}</strong><small>{action.danger.toUpperCase()} DANGER · {action.interruptible ? 'INTERRUPTIBLE' : 'UNINTERRUPTIBLE'}</small>{current && <ProgressBar value={combatProgress(selectedEnemy.currentAction!.remainingSeconds, selectedEnemy.currentAction!.totalSeconds)} variant="attack" />}</div> })}</div>}<AffinityRow label="WEAKNESS" values={definition.weaknesses} tone="weakness" /> <AffinityRow label="RESISTANCE" values={definition.resistances} tone="resistance" /><div className="reward-preview"><span className="tiny-label">KNOWN DROPS</span><div className="drop-list">{definition.loot.map((drop) => <span key={drop.itemId}><Sparkles size={11} /> <strong>{itemById[drop.itemId]?.name ?? drop.itemId}</strong><small>{Math.round(drop.chance * 100)}%{drop.maxQuantity > 1 ? ` · ×${drop.minQuantity}-${drop.maxQuantity}` : ''}</small></span>)}</div></div></> : <div className="empty-state"><Target size={24} /><strong>No active enemy group</strong><p>Start a Combat Location Hunt to generate one.</p></div>}
  </Panel>
}

function TargetStat({ label, value }: { label: string; value: string | number }) { return <div><span>{label}</span><strong>{value}</strong></div> }
function AffinityRow({ label, values, tone }: { label: string; values: string[]; tone: 'weakness' | 'resistance' }) { if (values.length === 0) return null; return <div className={`affinity-row ${tone}`}><span className="tiny-label">{label}</span><div>{values.map((value) => <span key={value}>{value}</span>)}</div></div> }
