import { useEffect, useMemo, useState } from "react";
import type { PlayerActionDefinition } from "../../../../game/combat/combatTypes";
import { isCombatAbilityLoadoutAction } from "../../../../game/combat/playerActions";
import { getCombatAbilityAvailability } from "../../../../game/combatAbilities/combatAbilitySelectors";
import { automationPresetConfigEquals, snapshotAutomationConfig, type CombatAutomationPreset } from "../../../../game/automation/automationPresets";
import type { GameState } from "../../../../game/gameState";
import { useGameStore } from "../../../../state/gameStore";

export function AutomationPresetsPanel({ game, actions, onLoaded }: { game: GameState; actions: PlayerActionDefinition[]; onLoaded?: (slot: number) => void }) {
  const savePreset = useGameStore((state) => state.saveAutomationPreset);
  const loadPreset = useGameStore((state) => state.loadAutomationPreset);
  const renamePreset = useGameStore((state) => state.renameAutomationPreset);
  const clearPreset = useGameStore((state) => state.clearAutomationPreset);
  const [selectedSlot, setSelectedSlot] = useState<number | null>(() => game.combatAutomationPresets.slots.findIndex(Boolean) >= 0 ? game.combatAutomationPresets.slots.findIndex(Boolean) : null);
  const [renamingSlot, setRenamingSlot] = useState<number | null>(null);
  const [renameValue, setRenameValue] = useState("");
  const currentConfig = useMemo(() => snapshotAutomationConfig(game.combatAutomation), [game.combatAutomation]);
  const selectedPreset = selectedSlot === null ? undefined : game.combatAutomationPresets.slots[selectedSlot] ?? undefined;
  useEffect(() => { if (selectedSlot !== null && game.combatAutomationPresets.slots[selectedSlot]) return; const first = game.combatAutomationPresets.slots.findIndex(Boolean); setSelectedSlot(first >= 0 ? first : null); }, [game.combatAutomationPresets.slots, selectedSlot]);
  const isCurrentMatch = (preset: CombatAutomationPreset | null) => Boolean(preset && automationPresetConfigEquals(currentConfig, preset.config));
  const unavailableActionCount = (preset: CombatAutomationPreset) => preset.config.rules.filter((rule) => { const action = actions.find((candidate) => candidate.id === rule.actionId); if (!action) return true; return isCombatAbilityLoadoutAction(action) && (!game.combatAbilities.slots.includes(action.id) || !getCombatAbilityAvailability(game, action.id).usable); }).length;
  const beginRename = (preset: CombatAutomationPreset, slot: number) => { setRenamingSlot(slot); setRenameValue(preset.name); };
  const commitRename = (slot: number) => { renamePreset(slot, renameValue); setRenamingSlot(null); };
  return <section className="automation-presets" data-debug-kind="automation-presets" aria-label="Automation presets">
    <div className="section-title"><div><span className="tiny-label">AUTOMATION PRESETS</span><p className="muted-copy">Save and reuse action rules.</p></div><span className="automation-preset-count">{game.combatAutomationPresets.slots.filter(Boolean).length} / 10 SAVED</span></div>
    <div className="automation-preset-grid">{game.combatAutomationPresets.slots.map((preset, slot) => { const currentMatch = isCurrentMatch(preset); return <div key={slot} className={`automation-preset-slot ${preset ? "is-occupied" : "is-empty"} ${selectedSlot === slot ? "is-selected" : ""} ${currentMatch ? "is-current" : ""}`} data-debug-kind="automation-preset" data-debug-slot={slot}>{preset ? <button className="automation-preset-slot-button" onClick={() => { setSelectedSlot(slot); setRenamingSlot(null); }} aria-label={`Select preset ${slot + 1}: ${preset.name}`}><span className="tiny-label">SLOT {slot + 1}</span><strong>{preset.name}</strong><small>{preset.config.rules.length} rules</small><em>{currentMatch ? "CURRENT SETUP" : "SAVED SETUP"}</em></button> : <><span className="tiny-label">SLOT {slot + 1}</span><strong>EMPTY</strong><small>Save the current automation setup here.</small><button className="button button-ghost compact" onClick={() => { savePreset(slot); setSelectedSlot(slot); }}>SAVE CURRENT</button></>}</div> })}</div>
    {selectedPreset && selectedSlot !== null && <div className="automation-preset-detail" data-debug-kind="automation-preset-detail"><div className="automation-preset-detail-heading"><div><span className="tiny-label">SELECTED PRESET · SLOT {selectedSlot + 1}</span>{renamingSlot === selectedSlot ? <div className="automation-preset-rename"><input value={renameValue} maxLength={32} autoFocus onChange={(event) => setRenameValue(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter") commitRename(selectedSlot); if (event.key === "Escape") setRenamingSlot(null); }} aria-label="Preset name" /><button className="button button-primary compact" onClick={() => commitRename(selectedSlot)}>SAVE NAME</button><button className="button button-ghost compact" onClick={() => setRenamingSlot(null)}>CANCEL</button></div> : <h3>{selectedPreset.name}</h3>}</div><div className="automation-preset-detail-meta"><span>{selectedPreset.config.rules.length} rules</span><span>{unavailableActionCount(selectedPreset)} unavailable actions</span></div></div><ol>{[...selectedPreset.config.rules].sort((a, b) => a.priority - b.priority || a.id.localeCompare(b.id)).slice(0, 4).map((rule) => <li key={rule.id}><strong>{rule.priority}</strong> {actions.find((action) => action.id === rule.actionId)?.name ?? rule.actionId}{!rule.enabled && " · disabled"}</li>)}</ol><div className="hero-inline-actions"><button className="button button-primary" onClick={() => { loadPreset(selectedSlot); onLoaded?.(selectedSlot); }}>LOAD PRESET</button><button className="button button-ghost" onClick={() => savePreset(selectedSlot)}>OVERWRITE</button><button className="button button-ghost" onClick={() => beginRename(selectedPreset, selectedSlot)}>RENAME</button><button className="button button-danger" onClick={() => { clearPreset(selectedSlot); setSelectedSlot(null); }}>DELETE</button></div></div>}
  </section>;
}
