import type { ReactNode } from 'react'
import { Crosshair, Heart, Pause, Play, Shield, Sparkles, Swords, Target, Timer, Zap } from 'lucide-react'
import { enemyById } from '../../../game/data/enemies'
import { itemById } from '../../../game/data/items'
import { spellDefinitions } from '../../../game/data/spells'
import { stanceDefinitions } from '../../../game/data/stances'
import { techniqueDefinitions } from '../../../game/data/techniques'
import { combatLocationById } from '../../../game/data/world/combatLocations'
import type { TechniqueId } from '../../../game/combat/combatTypes'
import { calculateHunterCombatStats } from '../../../game/equipment/derivedStats'
import { useGameStore } from '../../../state/gameStore'
import { Panel } from '../../components/Panel'
import { PlaceholderArt } from '../../components/PlaceholderArt'
import { ProgressBar } from '../../components/ProgressBar'
import { SegmentedTabs } from '../../components/SegmentedTabs'
import { StatLine } from '../../components/StatLine'
import { ScreenHeading } from '../../shell/ScreenHeading'
import { CombatWorldBrowser } from './CombatWorldBrowser'

export function CombatScreen() {
  const game = useGameStore((state) => state.game)
  const startHunt = useGameStore((state) => state.startHunt)
  const stopHunt = useGameStore((state) => state.stopHunt)
  const selectTarget = useGameStore((state) => state.selectTarget)
  const setStance = useGameStore((state) => state.setStance)
  const toggleTechnique = useGameStore((state) => state.toggleTechnique)
  const castSpell = useGameStore((state) => state.castSpell)
  const usePotion = useGameStore((state) => state.usePotion)
  const overviewTab = useGameStore((state) => state.combatOverviewTab)
  const setOverviewTab = useGameStore((state) => state.setCombatOverviewTab)
  const combat = game.combat
  const location = combat.combatLocationId ? combatLocationById[combat.combatLocationId] : undefined
  const selectedEnemy = combat.enemies.find((enemy) => enemy.instanceId === combat.selectedEnemyInstanceId) ?? combat.enemies.find((enemy) => !enemy.defeated)
  const selectedDefinition = selectedEnemy ? enemyById[selectedEnemy.enemyId] : enemyById['enemy.grey-wolf']
  const stats = calculateHunterCombatStats(game.equipment, game.progression, combat.stance, combat.techniques)
  const active = combat.phase === 'active' || combat.phase === 'recovery'

  return <div className="screen combat-screen" data-debug-screen="combat">
    <ScreenHeading screen="combat" />
    <CombatWorldBrowser />
    <div className="combat-main-grid">
      <Panel title="Hunter" subtitle="Preparation and derived stats" icon={Shield} panelId="playerCombat" screen="combat" className="player-combat-panel">
        <div className="combat-identity"><PlaceholderArt icon="shield" label="Vanguard" size="large" variant="blue" /><div><h3>Vanguard</h3><p>Hunter Rank {game.progression.hunterRank}</p><span className="identity-level">Combat Level {Object.values(game.progression.skills).reduce((sum, skill) => sum + skill.level, 0)}</span></div></div>
        <div className="focus-box"><span className="tiny-label">ACTIVE TRAINING</span><strong>{game.progression.trainingFocus}</strong><small>Enemy victories award XP here.</small></div>
        <div className="stance-section"><div className="section-title"><span className="tiny-label">STANCE</span><small>{combat.stanceCooldownRemaining > 0 ? `${combat.stanceCooldownRemaining.toFixed(1)}s cooldown` : 'Ready'}</small></div><div className="stance-buttons">{(Object.keys(stanceDefinitions) as Array<'high' | 'mid' | 'low'>).map((stance) => <button key={stance} className={combat.stance === stance ? 'stance-button is-active' : 'stance-button'} onClick={() => setStance(stance)} disabled={combat.stanceCooldownRemaining > 0} data-debug-kind="stance" data-debug-stance-id={`stance.${stance}`}>{stanceDefinitions[stance].name}</button>)}</div><p className="micro-copy">{stanceDefinitions[combat.stance].description}</p></div>
        <div className="stat-stack"><StatLine label="Attack" value={stats.attack} accent="gold" /><StatLine label="Accuracy" value={stats.accuracy} /><StatLine label="Defense" value={stats.defense} accent="blue" /><StatLine label="Attack interval" value={`${stats.attackInterval.toFixed(1)}s`} /></div>
        <div className="technique-list"><span className="tiny-label">SUSTAINED TECHNIQUES</span>{(Object.keys(techniqueDefinitions) as TechniqueId[]).map((id) => <button key={id} className={`technique-row ${combat.techniques[id] ? 'is-active' : ''}`} onClick={() => toggleTechnique(id)} data-debug-kind="technique" data-debug-technique-id={`technique.${id}`}><span className="technique-toggle" /><span><strong>{techniqueDefinitions[id].name}</strong><small>{techniqueDefinitions[id].drainPerSecond} Energy/s · {techniqueDefinitions[id].description}</small></span></button>)}</div>
      </Panel>
      <Panel title="Live hunt" subtitle={active ? `${location?.name ?? 'Combat Location'} · Group ${combat.groupNumber} · ${combat.enemies.filter((enemy) => !enemy.defeated).length} enemies alive` : combat.stopReason ? `Stopped: ${combat.stopReason}` : 'Start a Combat Location Hunt to generate a group'} icon={Swords} panelId="liveCombat" screen="combat" className="live-combat-panel">
        <div className={`combat-status ${combat.phase === 'active' ? 'is-active' : ''}`}><span className="status-pulse" /><span>{combat.phase === 'active' ? 'LIVE HUNT' : combat.phase === 'recovery' ? 'GROUP RECOVERY' : combat.phase.toUpperCase()}</span><span className="combat-round">GROUP {combat.groupNumber || '—'}</span></div>
        <div className="resource-display"><Resource label="HP" value={combat.playerHp} max={stats.maxHealth} icon={<Heart size={13} />} variant="health" /><Resource label="Energy" value={combat.energy} max={combat.maxEnergy} icon={<Zap size={13} />} variant="resource" /><Resource label="Adrenaline" value={combat.adrenaline} max={combat.maxAdrenaline} icon={<Sparkles size={13} />} variant="experience" /></div>
        <div className="enemy-roster" aria-label="Generated hunt group">{combat.enemies.map((enemy) => { const definition = enemyById[enemy.enemyId]; const action = enemy.currentAction ? definition.actions.find((candidate) => candidate.id === enemy.currentAction?.actionId) : undefined; const targeted = enemy.instanceId === combat.selectedEnemyInstanceId; return <button key={enemy.instanceId} className={`enemy-combat-card ${targeted ? 'is-targeted' : ''} ${enemy.defeated ? 'is-defeated' : ''}`} onClick={() => selectTarget(enemy.instanceId)} aria-pressed={targeted} data-debug-kind="combat-enemy" data-debug-enemy-id={enemy.enemyId} data-debug-instance-id={enemy.instanceId} data-debug-label={enemy.displayName}><div className="enemy-card-top"><PlaceholderArt icon={definition.icon} size="small" variant={definition.accent} /><span><strong>{targeted && <Crosshair size={11} />} {enemy.displayName}</strong><small>{enemy.defeated ? 'DEFEATED' : `${enemy.currentHealth} / ${enemy.maxHealth} HP`}</small></span><em>{targeted ? 'TARGETED' : enemy.defeated ? 'CLEARED' : 'SELECT'}</em></div>{!enemy.defeated && <><ProgressBar value={(enemy.currentHealth / enemy.maxHealth) * 100} variant="health" /><div className="enemy-card-timer"><span><Timer size={11} /> Attack</span><strong>{Math.max(0, enemy.attackTimer).toFixed(1)}s</strong></div>{action && <div className={`special-intent danger-${action.danger}`}><div><span>{action.name}</span><strong>{Math.max(0, enemy.currentAction!.remainingSeconds).toFixed(1)}s</strong></div><ProgressBar value={(1 - enemy.currentAction!.remainingSeconds / enemy.currentAction!.totalSeconds) * 100} variant="attack" /><small>{action.danger.toUpperCase()} DANGER · {action.interruptible ? 'INTERRUPTIBLE' : 'UNINTERRUPTIBLE'}</small></div>}</>}</button> })}</div>
        <div className="spell-controls"><div className="section-title"><span className="tiny-label">SPELLS</span><small>Adrenaline {Math.floor(combat.adrenaline)} / {combat.maxAdrenaline}</small></div><div className="spell-grid">{spellDefinitions.map((spell) => { const runtime = combat.spells.find((entry) => entry.spellId === spell.id); const selectedAction = selectedEnemy?.currentAction ? selectedDefinition.actions.find((action) => action.id === selectedEnemy.currentAction?.actionId) : undefined; const valid = combat.phase === 'active' && (runtime?.cooldownRemaining ?? 1) <= 0 && combat.adrenaline >= spell.cost && (spell.id !== 'spell.disrupting-pulse' || Boolean(selectedAction?.interruptible)); return <button key={spell.id} className={`spell-button ${valid ? 'is-ready' : ''}`} onClick={() => castSpell(spell.id)} disabled={!valid} data-debug-kind="spell" data-debug-spell-id={spell.id}><PlaceholderArt icon={spell.icon} size="small" variant={valid ? 'gold' : 'muted'} /><span><strong>{spell.name}</strong><small>{runtime?.cooldownRemaining && runtime.cooldownRemaining > 0 ? `${runtime.cooldownRemaining.toFixed(1)}s` : `${spell.cost} ADR`}</small></span></button> })}</div></div>
        <div className="combat-controls"><button aria-label={active ? 'Stop hunt' : 'Start hunt'} className="button button-primary fight-button" onClick={active ? stopHunt : startHunt} data-debug-kind="combat-control" data-debug-label={active ? 'Stop hunt' : 'Start hunt'}>{active ? <><Pause size={16} />Stop Hunt</> : <><Play size={16} />Start Hunt</>}</button><button className="button button-secondary" onClick={usePotion} disabled={combat.phase !== 'active' || (game.inventory.quantities['item.healing-potion'] ?? 0) <= 0}><Heart size={14} />Potion ×{game.inventory.quantities['item.healing-potion'] ?? 0}</button><span className="control-hint"><Timer size={13} /> Random groups continue automatically</span></div>
        <div className="combat-log" data-debug-kind="combat-log"><div className="combat-log-heading"><span className="tiny-label">HUNT LOG</span><span>{combat.log.length} recent events</span></div><div className="combat-log-list">{combat.log.slice(0, 7).map((entry) => <div className={`combat-log-entry log-${entry.type}`} key={entry.id}><time>{entry.time}</time><span>{entry.text}</span></div>)}</div></div>
      </Panel>
      <Panel title="Selected enemy" subtitle="Current runtime target" icon={Target} panelId="targetCombat" screen="combat" className="target-combat-panel">
        {selectedEnemy ? <><div className="target-card-top"><PlaceholderArt icon={selectedDefinition.icon} label={selectedEnemy.displayName} size="medium" variant={selectedDefinition.accent} /><div><h3>{selectedEnemy.displayName}</h3><p>{selectedDefinition.family} · Group {combat.groupNumber}</p><span className="level-badge">{selectedEnemy.defeated ? 'DEFEATED' : `INSTANCE ${selectedEnemy.instanceId.split('#')[1]}`}</span></div></div><div className="target-stat-grid"><div><span>Attack</span><strong>{selectedDefinition.attack}</strong></div><div><span>Defense</span><strong>{selectedDefinition.defense}</strong></div><div><span>XP</span><strong>{selectedDefinition.baseXp}</strong></div></div><div className="trait-section"><span className="tiny-label">TRAITS</span><div>{selectedDefinition.traits.map((trait) => <span className="trait-chip" key={trait.id}>{trait.name}</span>)}</div><p className="micro-copy">{selectedDefinition.traits[0]?.description}</p></div>{selectedEnemy.currentAction && <div className="selected-special"><span className="tiny-label">CURRENT SPECIAL</span><strong>{selectedDefinition.actions.find((action) => action.id === selectedEnemy.currentAction?.actionId)?.name}</strong><small>{selectedEnemy.currentAction.remainingSeconds.toFixed(1)}s remaining · {selectedDefinition.actions.find((action) => action.id === selectedEnemy.currentAction?.actionId)?.interruptible ? 'interruptible' : 'uninterruptible'}</small></div>}<div className="reward-preview"><span className="tiny-label">KNOWN DROPS</span><div>{selectedDefinition.loot.map((drop) => <span key={drop.itemId}><Sparkles size={12} /> {itemById[drop.itemId]?.name ?? drop.itemId}</span>)}</div></div></> : <div className="empty-state"><Target size={24} /><strong>No active enemy group</strong><p>Start a Combat Location Hunt to generate one.</p></div>}
      </Panel>
    </div>
    <Panel title="Hunt session overview" subtitle="Rewards and progression across generated groups" icon={Zap} panelId="combatOverview" screen="combat" actions={<SegmentedTabs items={['Session Summary', 'Rewards', 'Progression'] as const} active={overviewTab} onChange={setOverviewTab} label="Hunt overview" />}>
      {overviewTab === 'Session Summary' && <div className="overview-tab-grid"><StatLine label="Elapsed time" value={`${Math.floor(combat.session.elapsedSeconds)}s`} /><StatLine label="Groups cleared" value={combat.session.groupClears} accent="gold" /><StatLine label="Enemies defeated" value={combat.session.enemiesDefeated} /><StatLine label="Highest hit" value={combat.session.highestHit} accent="green" /><div className="overview-note"><span className="status-dot" />{combat.stopReason ? `Last stop: ${combat.stopReason}` : 'Individual rewards remain permanent across the Hunt session.'}</div></div>}
      {overviewTab === 'Rewards' && <div className="overview-tab-grid reward-overview"><StatLine label="XP gained" value={combat.session.xpGained} accent="gold" /><StatLine label="Items gained" value={combat.session.itemsGained} /><StatLine label="Gold gained" value={combat.session.goldGained} accent="gold" /><StatLine label="Healing" value={combat.session.healing} accent="green" /><div className="overview-note">{Object.entries(combat.session.lootGained).map(([itemId, quantity]) => `${itemById[itemId]?.name ?? itemId} ×${quantity}`).join(' · ') || 'No loot recorded in this Hunt yet.'}</div></div>}
      {overviewTab === 'Progression' && <div className="overview-tab-grid"><StatLine label="Training focus" value={game.progression.trainingFocus} accent="gold" /><StatLine label="Hunter Rank" value={game.progression.hunterRank} /><StatLine label="Total Combat Level" value={Object.values(game.progression.skills).reduce((sum, skill) => sum + skill.level, 0)} /><div className="overview-note">Each enemy defeat awards XP to the active training focus.</div></div>}
    </Panel>
  </div>
}

function Resource({ label, value, max, icon, variant }: { label: string; value: number; max: number; icon: ReactNode; variant: 'health' | 'resource' | 'experience' }) { return <div className="resource-block"><div><span>{icon} {label}</span><strong>{Math.floor(value)} / {max}</strong></div><ProgressBar value={(value / max) * 100} variant={variant} /></div> }
